[package]
name = "sqlscope-python"
description = "Python bindings for sqlscope"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
name = "_native"
crate-type = ["cdylib"]

[dependencies]
sqlscope = { path = "../crates/sqlscope" }
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py39"] }

[build-dependencies]
pyo3-build-config = "0.29"
