from typing import Dict, List, Optional, Tuple

__version__: str

class Error(Exception): ...
class InvalidArgumentError(Error): ...
class ParseError(Error): ...
class UnsupportedError(Error): ...
class InternalError(Error): ...

_Table = Tuple[str, Optional[str], Optional[str]]

def apply_row_filter(
    sql: str,
    predicate: str,
    dialect: Optional[str] = ...,
    table_names: Optional[List[str]] = ...,
    table_patterns: Optional[List[str]] = ...,
    default_db: Optional[str] = ...,
) -> str: ...
def inject_ctes(sql: str, ctes: List[Tuple[str, str]], dialect: Optional[str] = ...) -> str: ...
def rewrite_tables(
    sql: str,
    rewrites: List[Tuple[str, Optional[_Table], Optional[Tuple[str, List[str], List[_Table]]]]],
    dialect: Optional[str] = ...,
    strip_catalogs: Optional[List[str]] = ...,
) -> str: ...
def column_origins(
    sql: str, dialect: Optional[str] = ..., schema: Optional[Dict[str, List[str]]] = ...
) -> Dict[str, List[str]]: ...
def output_columns(
    sql: str, dialect: Optional[str] = ..., schema: Optional[Dict[str, List[str]]] = ...
) -> Optional[List[str]]: ...
def referenced_columns(
    sql: str, dialect: Optional[str] = ..., schema: Optional[Dict[str, List[str]]] = ...
) -> Dict[str, List[str]]: ...
def column_usages(
    sql: str, dialect: Optional[str] = ..., schema: Optional[Dict[str, List[str]]] = ...
) -> List[Tuple[str, str, str]]: ...
